<html>
   <body>
      <h3>PHP Session </h3>
      <pre>
         *** PHP session is used to store and pass information from one page to another 
            temporarily (until user close the website).
         *** PHP session technique is widely used in shopping websites 
               where we need to store and pass cart information. 
               Example:  username, product code, product name, product price etc from one page to another.

         *** PHP session creates unique user id for each browser to recognize the user 
               and avoid conflict between multiple browsers.
            * session_id() is used to get or set the session id for the current session.
                The constant SID can also be used to retrieve the current name and session id
                 as a string suitable for adding to URLs. 
         ** EXAMPLE :1
         session_start();   
         $id = session_id();
         print("Session Id: ".$id);

         *** Important Points
            * The session IDs are randomly generated by the PHP engine .
            * The session data is stored on the server therefore it doesn’t have to be sent 
               with every browser request.
            * The session_start() function needs to be called at the beginning of the page, 
                  before any output is generated by the script in the browser.

         *** PHP session - working
            * PHP session_start() function is used to start the session.
              - It starts a new or resumes existing session. 
              - If session is not available, it creates and returns new session.
              - It returns existing session if session is created already. 
             
            ** Syntax
               bool session_start ( void )  
               * Example
                  session_start();  

            ** PHP $_SESSION
               PHP $_SESSION is an associative array that contains all session variables.
                It is used to set and get session variable values.

               * Example: Store information
                  $_SESSION["user"] = "Sachin";  
               * Example: Get information
                  echo $_SESSION["user"]; 

        *** PHP Destroying Session
            * PHP session_destroy() function is used to destroy all session variables completely.


      </pre>        
   </body>
</html>
